// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelimAPI.Persistence.Contexts;

#nullable disable

namespace TelimAPI.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027070435_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelimAPI.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SelectionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingCourt", b =>
                {
                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainingId", "CourtId");

                    b.HasIndex("CourtId");

                    b.ToTable("TrainingCourt");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingDepartment", b =>
                {
                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainingId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TrainingDepartment");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerRating")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingParticipantId")
                        .IsUnique();

                    b.ToTable("TrainingFeedback");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsJoined")
                        .HasColumnType("bit");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingParticipants");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Department", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.Court", "Court")
                        .WithMany("Departments")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingCourt", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.Court", "Court")
                        .WithMany("TrainingCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelimAPI.Domain.Entities.Training", "Training")
                        .WithMany("TrainingCourts")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingDepartment", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.Department", "Department")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelimAPI.Domain.Entities.Training", "Training")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingFeedback", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.TrainingParticipant", "TrainingParticipant")
                        .WithOne()
                        .HasForeignKey("TelimAPI.Domain.Entities.TrainingFeedback", "TrainingParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingParticipant");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.TrainingParticipant", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.Training", "Training")
                        .WithMany("Participants")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelimAPI.Domain.Entities.User", "User")
                        .WithMany("TrainingParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("TelimAPI.Domain.Entities.Court", "Court")
                        .WithMany("Users")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TelimAPI.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Court", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("TrainingCourts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("TrainingDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.Training", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("TrainingCourts");

                    b.Navigation("TrainingDepartments");
                });

            modelBuilder.Entity("TelimAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("TrainingParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
